[global]
   disable netbios = yes
   server smb transports = 445

   aio read size  = 1
   aio write size = 1
   use sendfile   = yes
   vfs objects    = io_uring

   server signing     = default
   server smb encrypt = desired
   log level = 1

[media]
   path = /srv/media
   read only = no
   browseable = yes

   veto files = /.snapshots/

   valid users = @smb-media
   force group = +smb-media

   create mask = 0664
   directory mask = 2775
   inherit acls = yes
   inherit permissions = yes

[private]
   path = /srv/private/%U
   read only = no
   veto files = /.snapshots/
   valid users = %U
   force user = %U
   force group = root
   create mask = 0600
   directory mask = 0700
   browseable = yes

   root preexec = /usr/local/sbin/samba-mkdir-private.sh %U
   root preexec close = yes
